package com.example.plugins.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;employee_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.example.plugins.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.example.plugins.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see com.example.plugins.model.impl.EmployeeImpl
 * @see com.example.plugins.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public int getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(int primaryKey);

    /**
     * Returns the eid of this employee.
     *
     * @return the eid of this employee
     */
    public int getEid();

    /**
     * Sets the eid of this employee.
     *
     * @param eid the eid of this employee
     */
    public void setEid(int eid);

    /**
     * Returns the name of this employee.
     *
     * @return the name of this employee
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this employee.
     *
     * @param name the name of this employee
     */
    public void setName(String name);

    /**
     * Returns the address of this employee.
     *
     * @return the address of this employee
     */
    @AutoEscape
    public String getAddress();

    /**
     * Sets the address of this employee.
     *
     * @param address the address of this employee
     */
    public void setAddress(String address);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(com.example.plugins.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.example.plugins.model.Employee> toCacheModel();

    @Override
    public com.example.plugins.model.Employee toEscapedModel();

    @Override
    public com.example.plugins.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
